### ISSUE TITLE
Massive amount of failures concerning async in Jakarta EE 8 TCK samples

### ISSUE THREAD

**Issue by arjantijms** [piranhacloud/piranha#1161]
Nearly evert test in https://github.com/javaee-samples/jakartaee8-tck that passed before now throws:

```
javax.servlet.ServletException: java.lang.IllegalStateException: Async is not supported
	at org.jakartaee8.servlet.servletrequest.asynccontext.GenericTCKServlet.invokeTest(GenericTCKServlet.java:88)
	at org.jakartaee8.servlet.servletrequest.asynccontext.GenericTCKServlet.service(GenericTCKServlet.java:72)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:114)
	at cloud.piranha.security.exousia.AuthorizationFilter.doFilter(AuthorizationFilter.java:86)
	at cloud.piranha.security.exousia.AuthorizationFilter.doFilter(AuthorizationFilter.java:76)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:110)
	at cloud.piranha.security.eleos.AuthenticationFilter.doFilter(AuthenticationFilter.java:82)
	at cloud.piranha.security.eleos.AuthenticationFilter.doFilter(AuthenticationFilter.java:76)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:110)
	at cloud.piranha.security.exousia.AuthorizationPreFilter.doFilter(AuthorizationPreFilter.java:94)
	at cloud.piranha.security.exousia.AuthorizationPreFilter.doFilter(AuthorizationPreFilter.java:79)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:110)
	at cloud.piranha.webapp.impl.DefaultServletRequestDispatcher.request(DefaultServletRequestDispatcher.java:135)
	at cloud.piranha.webapp.impl.DefaultWebApplication.service(DefaultWebApplication.java:1573)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.service(DefaultWebApplicationServer.java:285)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.process(DefaultWebApplicationServer.java:244)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:85)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: Async is not supported
	at cloud.piranha.webapp.impl.DefaultWebApplicationRequest.startAsync(DefaultWebApplicationRequest.java:1586)
	at org.jakartaee8.servlet.servletrequest.asynccontext.AsyncTestServlet.dispatchContextPathTest1(AsyncTestServlet.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jakartaee8.servlet.servletrequest.asynccontext.GenericTCKServlet.invokeTest(GenericTCKServlet.java:86)
	... 19 more
javax.servlet.ServletException: java.lang.IllegalStateException: Async is not supported
	at org.jakartaee8.servlet.servletrequest.asynccontext.GenericTCKServlet.invokeTest(GenericTCKServlet.java:88)
	at org.jakartaee8.servlet.servletrequest.asynccontext.GenericTCKServlet.service(GenericTCKServlet.java:72)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:114)
	at cloud.piranha.security.exousia.AuthorizationFilter.doFilter(AuthorizationFilter.java:86)
	at cloud.piranha.security.exousia.AuthorizationFilter.doFilter(AuthorizationFilter.java:76)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:110)
	at cloud.piranha.security.eleos.AuthenticationFilter.doFilter(AuthenticationFilter.java:82)
	at cloud.piranha.security.eleos.AuthenticationFilter.doFilter(AuthenticationFilter.java:76)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:110)
	at cloud.piranha.security.exousia.AuthorizationPreFilter.doFilter(AuthorizationPreFilter.java:94)
	at cloud.piranha.security.exousia.AuthorizationPreFilter.doFilter(AuthorizationPreFilter.java:79)
	at cloud.piranha.webapp.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:110)
	at cloud.piranha.webapp.impl.DefaultServletRequestDispatcher.request(DefaultServletRequestDispatcher.java:135)
	at cloud.piranha.webapp.impl.DefaultWebApplication.service(DefaultWebApplication.java:1573)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.service(DefaultWebApplicationServer.java:285)
	at cloud.piranha.appserver.impl.DefaultWebApplicationServer.process(DefaultWebApplicationServer.java:244)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:85)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: Async is not supported
	at cloud.piranha.webapp.impl.DefaultWebApplicationRequest.startAsync(DefaultWebApplicationRequest.java:1586)
	at org.jakartaee8.servlet.servletrequest.asynccontext.AsyncTestServlet.dispatchContextPathTest1(AsyncTestServlet.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jakartaee8.servlet.servletrequest.asynccontext.GenericTCKServlet.invokeTest(GenericTCKServlet.java:86)
	... 19 more
```

**Comment by Thihup** [comment]
Looks like the security filters (Eleos and Exousia) aren't declared as async supported thus making all servlets as async not supported. As the Piranha server whose runs the full TCK don't use it, it didn't fail.
Probably declaring these filters as async-supported should do the work (and set up a pipeline to run the Jakarta EE 8 TCK samples would be good too)

**Comment by manorrock** [comment]
Yes on setting up those in external/jakartaee8-samples !
