### ISSUE TITLE
HTTP/2 implementation

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#1249]
We need to have an HTTP/2 implementation to pass the Server Push tests from the Servlet TCK.
Should we create a new HTTP/2 server implementation or should we use some of the implementations that are HTTP/2 compliant (like Undertow, Grizzly, ...).

I'm afraid that implementing a new HTTP/2 may be a lot of new code. If we decide to create a new implementation, should it be a new module (like http-impl2) or should it be embedded in the impl module?

**Comment by manorrock** [comment]
I am fine if we use any of the implementations that already support HTTP/2

**Comment by arjantijms** [comment]
+1 reuse as much as possible, so in this case specifically as much from Grizzly since we're using that as the default anyway.

**Comment by Thihup** [comment]
Alright! I'll run some tests with Grizzly.

**Comment by manorrock** [comment]
As far as I know we are still using http/impl module, not Grizzly. Note in principal all the HTTP engines that support HTTP/2 should then be able to pass those tests.

**Comment by arjantijms** [comment]
> As far as I know we are still using http/impl module, not Grizzly. 

You're right, I was wrong. http/impl is now the default. I somehow thought we had already switched to Grizzly as the default, but we didn't. My bad.

**Comment by Thihup** [comment]
I've run some tests with Grizzly and Undertow and both easily supported the HTTP/2 connection.
However, a lot of Servlet TCK tests (mainly the async tests) failed using either of them.

I've noticed something a little bit off too. Today the webapp-impl depends on the http-impl without real use. I thought we could remove the http dependency completely, but we'll need it to communicate the server push from the servlet context to the http implementation (so the http-api may be sufficient)

I couldn't get the Netty to work with HTTP/2 mainly because I couldn't figure out how to enable it.

Using the Undertow, we get a lot of this exception:
```
IOException when flushing the underlying async output stream
java.io.IOException: UT000034: Stream is closed
        at undertow.core/io.undertow.io.UndertowOutputStream.flush(UndertowOutputStream.java:275)
        at cloud.piranha.http.api/cloud.piranha.http.api.HttpServerResponse.closeResponse(HttpServerResponse.java:96)
        at cloud.piranha.appserver.impl/cloud.piranha.appserver.impl.DefaultWebApplicationServer.lambda$createResponse$2(DefaultWebApplicationServer.java:193)
        at cloud.piranha.appserver.impl/cloud.piranha.appserver.impl.DefaultWebApplicationServer$$Lambda$245/0x000000004cd6dc50.run(Unknown Source)
        at cloud.piranha.appserver.impl/cloud.piranha.appserver.impl.DefaultWebApplicationServerResponse.closeAsyncResponse(DefaultWebApplicationServerResponse.java:64)
        at cloud.piranha.webapp.impl/cloud.piranha.webapp.impl.DefaultAsyncContext.onTimeOut(DefaultAsyncContext.java:292)
        at cloud.piranha.webapp.impl/cloud.piranha.webapp.impl.DefaultAsyncContext$$Lambda$247/0x000000004cd6e238.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:845)
```

And using Grizzly:
```
java.lang.NullPointerException: Cannot invoke "org/glassfish/grizzly/http/io/OutputBuffer.write([B)V"
        at grizzly.http.server/org.glassfish.grizzly.http.server.NIOOutputStreamImpl.write(NIOOutputStreamImpl.java:51)
        at cloud.piranha.webapp.impl/cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeStatusLine(DefaultWebApplicationResponse.java:1055)
        at cloud.piranha.webapp.impl/cloud.piranha.webapp.impl.DefaultWebApplicationResponse.writeOut(DefaultWebApplicationResponse.java:1027)
        at cloud.piranha.webapp.impl/cloud.piranha.webapp.impl.DefaultWebApplicationResponse.flushBuffer(DefaultWebApplicationResponse.java:314)
        at cloud.piranha.webapp.impl/cloud.piranha.webapp.impl.DefaultAsyncContext.complete(DefaultAsyncContext.java:258)
        at com.sun.ts.tests.servlet.api.javax_servlet.asynccontext.AsyncTestServlet$2.run(AsyncTestServlet.java:391)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by manorrock** [comment]
OK lets untangle webapp-impl from http-impl first. Good catch! And then come up with the proper API each of the HTTP engine can implement if they want to support HTTP/2. And then we'll have to adjust our async code accordingly

**Comment by Thihup** [comment]
I started a run of the Servlet TCK with all implementations (https://github.com/piranhacloud/piranha/actions/runs/366177372). 

Except for Impl and JDK, all other implementations handle the header itself and the OutputStream is only provided for the body. So it causes the status code being sent twice.

For some reason, the Netty implementation could not finish the TCK. It stuck on a test and the timeout of a Github action is 6 hours, so it was canceled.

|Implementation | Java version | Tests Passed | Tests Failed | Tests Error |
|---------------------|-------------------|-------------------|-------------------|---------------|
|Grizzly|8|1,307|383|0|
|Grizzly|15|1,306|384|0|
|Impl|8|1,514|163|13|
|Impl|15|1,513|171|6|
|JDK|8|1,515|162|13|
|JDK|15|1,513|171|6|
|Netty|8|444|104|33|
|Netty|15|445|103|33|
|Undertow|8|1,303|386|1|
|Undertow|15|1,302|387|1|

**Comment by manorrock** [comment]
I am already working on changing the DefaultWebApplicationResponse class to fix the header problem
