### ISSUE TITLE
OmniFaces 4.x IT fails with WELD-001414 on "csfFLOWDISCOVERYCDIHELPER"

### ISSUE THREAD

**Issue by BalusC** [piranhacloud/piranha#1444]
Pull https://github.com/omnifaces/omnifaces/commit/8640c85afa6a25d76d39e05a163170c49c3c4f0e

Run `mvn clean verify -Dmaven.javadoc.skip=true -Dit.test=ViewScopedIT -P piranha`

Observe
```
WARNING: Initializer cloud.piranha.security.jakarta.JakartaSecurityAllInitializer failing onStartup
org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name csfFLOWDISCOVERYCDIHELPER resolves to beans: [Managed Bean [class com.sun.faces.flow.FlowDiscoveryCDIHelper] with qualifiers [@Default @Any @Named], Managed Bean [class com.sun.faces.flow.FlowDiscoveryCDIHelper] with qualifiers [@Default @Any @Named]]
    at org.jboss.weld.bootstrap.Validator.validateBeanName(Validator.java:653)
    at org.jboss.weld.bootstrap.ConcurrentValidator$5.doWork(ConcurrentValidator.java:121)
    at org.jboss.weld.bootstrap.ConcurrentValidator$5.doWork(ConcurrentValidator.java:119)
    at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
    at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)
```

java -version
```
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

screenshot of /WEB-INF/lib of generated WAR:
![image](https://user-images.githubusercontent.com/173372/104616166-5c47f180-5660-11eb-83a8-0e02a731fcf3.png)

**Comment by Thihup** [comment]
I've run some tests and looks like the FlowDiscoveryCDIHelper is both being autodetected and added via FlowDiscoveryCDIExtension. The same issue happens to the beans declared in the com.sun.faces.cdi.CdiExtension::beforeBeanDiscovery.

Commenting both methods out, we get:
```
WARNING: Unable to initialize servlet: jakarta.faces.webapp.FacesServlet
java.lang.IllegalStateException: Could not find backup for factory jakarta.faces.context.FacesContextFactory. 
        at jakarta.faces.FactoryFinderInstance.notNullFactory(FactoryFinderInstance.java:496)
        at jakarta.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:190)
        at jakarta.faces.FactoryFinder.getFactory(FactoryFinder.java:264)
        at jakarta.faces.webapp.FacesServlet.acquireFacesContextFactory(FacesServlet.java:483)
        at jakarta.faces.webapp.FacesServlet.init(FacesServlet.java:328)
        at cloud.piranha.webapp.impl.DefaultWebApplication.initializeServlet(DefaultWebApplication.java:1503)
        at cloud.piranha.webapp.impl.DefaultWebApplication.lambda$initializeServlets$15(DefaultWebApplication.java:1445)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at cloud.piranha.webapp.impl.DefaultWebApplication.initializeServlets(DefaultWebApplication.java:1444)
        at cloud.piranha.webapp.impl.DefaultWebApplication.initialize(DefaultWebApplication.java:1324)
        at cloud.piranha.micro.core.MicroInnerDeployer.start(MicroInnerDeployer.java:233)
```

I will try to get more information about it.

**Comment by arjantijms** [comment]
Our Weld integration likely doesn't automatically follow the rule that any archive that has a CDI extension present should not be scanned for beans.

**Comment by arjantijms** [comment]
Could be related to the way we create and hand the jandex index to Weld, as Weld has to know which set of classes correspond to which jar (and associated bean.xml) in order to determine which classes to use or not.

**Comment by Thihup** [comment]
Looks like all classes are handed to Weld as a single "jar", even if a jar includes a beans.xml with bean-discovery-mode="none"

**Comment by arjantijms** [comment]
I figured something like that. We've to investigate to see if we need to create an index per jar and hand that to Weld, or whether jandex tracks classes back to each jar it scanned, and can ask for a beans.xml and META-INF/services/... file specific for that jar.

**Comment by Thihup** [comment]
The jandex only allows to store information about the classes, but not resources. On the other hand, looks like the [ClassGraph] supports it. I'll give it a try and see if maybe we can rework to use it instead of the Jandex (maybe together?).

[ClassGraph]: https://github.com/classgraph/classgraph

**Comment by arjantijms** [comment]
Weld itself uses Jandex natively as well, so might be a good idea to see how this is "normally" by Weld.
