### ISSUE TITLE
NPE at random time when accessing via web browser

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2580]
**Describe the bug**
Sometimes this is logged in the console. I think might the web browser tries to do some requests when the page is idle or something like that.

Probably adding a null check 
```shell
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "servletPath" is null
	at cloud.piranha.core.impl@22.5.0/cloud.piranha.core.impl.DefaultInvocationFinder.findServletInvocationByPath(DefaultInvocationFinder.java:109)
	at cloud.piranha.core.impl@22.5.0/cloud.piranha.core.impl.DefaultInvocationFinder.findServletInvocationByPath(DefaultInvocationFinder.java:88)
	at cloud.piranha.core.impl@22.5.0/cloud.piranha.core.impl.DefaultWebApplication.service(DefaultWebApplication.java:1211)
	at cloud.piranha.embedded@22.5.0/cloud.piranha.embedded.EmbeddedPiranha.service(EmbeddedPiranha.java:157)
	at cloud.piranha.http.webapp@22.5.0/cloud.piranha.http.webapp.HttpWebApplicationServerProcessor.process(HttpWebApplicationServerProcessor.java:69)
	at cloud.piranha.http.impl@22.5.0/cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1585)
```

**Comment by mnriem** [comment]
@Thihup Thanks for reporting the issue!
