### ISSUE TITLE
Error converting header to date

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#2950]
Trying to build Piranha in WSL leads to the following test failure

```java
[INFO] Running cloud.piranha.http.webapp.HttpWebApplicationRequestTest
out. 24, 2022 10:24:47 PM cloud.piranha.http.webapp.HttpWebApplicationServer process
SEVERE: An error occurred while processing the request
java.lang.IllegalArgumentException: Cannot convert header to a date
        at cloud.piranha.http.webapp@22.11.0-SNAPSHOT/cloud.piranha.http.webapp.HttpWebApplicationRequest.getDateHeader(HttpWebApplicationRequest.java:91)
        at cloud.piranha.http.webapp@22.11.0-SNAPSHOT/cloud.piranha.http.webapp.TestSnoopServlet.testGetDateHeader(TestSnoopServlet.java:224)
        at cloud.piranha.http.webapp@22.11.0-SNAPSHOT/cloud.piranha.http.webapp.TestSnoopServlet.processRequest(TestSnoopServlet.java:170)
        at cloud.piranha.http.webapp@22.11.0-SNAPSHOT/cloud.piranha.http.webapp.TestSnoopServlet.doGet(TestSnoopServlet.java:187)
        at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
        at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
        at cloud.piranha.core.impl@22.11.0-SNAPSHOT/cloud.piranha.core.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:113)
        at cloud.piranha.core.impl@22.11.0-SNAPSHOT/cloud.piranha.core.impl.DefaultServletRequestDispatcher.request(DefaultServletRequestDispatcher.java:163)
        at cloud.piranha.core.impl@22.11.0-SNAPSHOT/cloud.piranha.core.impl.DefaultWebApplication.service(DefaultWebApplication.java:1186)
        at cloud.piranha.http.webapp@22.11.0-SNAPSHOT/cloud.piranha.http.webapp.HttpWebApplicationServer.service(HttpWebApplicationServer.java:168)
        at cloud.piranha.http.webapp@22.11.0-SNAPSHOT/cloud.piranha.http.webapp.HttpWebApplicationServer.process(HttpWebApplicationServer.java:127)
        at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.text.ParseException: Unparseable date: "Wed, 16 Oct 2019 07:28:00 GMT"
        at java.base/java.text.DateFormat.parse(DateFormat.java:399)
        at cloud.piranha.http.webapp@22.11.0-SNAPSHOT/cloud.piranha.http.webapp.HttpWebApplicationRequest.getDateHeader(HttpWebApplicationRequest.java:89)
        ... 14 more
```

**Comment by Thihup** [comment]
Probably we are relying on the default locale to convert the date, and using a custom locale leads to failure in parsing the date.

**Comment by mnriem** [comment]
This might be the fallout from refactoring the HttpWebApplicationServer to use the HttpWebApplicationRequest instead of the DefaultWebApplicationRequest. This was needed so we can support HTTP/2 by switching to an HTTP engine that supports it.
