### ISSUE TITLE
RuntimeException when application is not yet ready

### ISSUE THREAD

**Issue by rdebusscher** [piranhacloud/piranha#3286]
When you call the endpoints of the application that is not yet ready (is still in the process of being deployed) you get following exceptions in the log.

This can result in false notifications when you process the log automatically.

```
java -jar piranha-dist-coreprofile-23.2.0.jar --context-path ROOT --war-file ../target/piranha.war &
curl localhost:8080/hello/Testing
```
Log

```
Mar 04, 2023 7:11:10 PM cloud.piranha.http.webapp.HttpWebApplicationServer process
SEVERE: An error occurred while processing the request
java.lang.RuntimeException: Unable to service request
	at cloud.piranha.core.impl.DefaultWebApplication.verifyState(DefaultWebApplication.java:1366)
	at cloud.piranha.core.impl.DefaultWebApplication.service(DefaultWebApplication.java:1176)
	at cloud.piranha.http.webapp.HttpWebApplicationServer.service(HttpWebApplicationServer.java:172)
	at cloud.piranha.http.webapp.HttpWebApplicationServer.process(HttpWebApplicationServer.java:128)
	at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mar 04, 2023 7:11:10 PM cloud.piranha.dist.coreprofile.CoreProfilePiranha run
INFO: Started Piranha
Mar 04, 2023 7:11:10 PM cloud.piranha.dist.coreprofile.CoreProfilePiranha run
INFO: It took 1,041 milliseconds
```

Low priority

**Comment by mnriem** [comment]
@rdebusscher This fix will be released as part of the upcoming 23.3.0 release. Thanks for filing the bug!
