### ISSUE TITLE
Fix NullPointerException

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#3717]
How to reproduce:

1. Run Manorrock Calico
2. Browse to http://localhost:8080/calico/index.xhtml
3. See NullPointerException.

----
Stacktrace

java.lang.NullPointerException: Cannot invoke "org.glassfish.exousia.AuthorizationService.checkWebUserDataPermission(jakarta.servlet.http.HttpServletRequest)" because the return value of "cloud.piranha.extension.security.servlet.ServletSecurityManager.getAuthorizationService(jakarta.servlet.http.HttpServletRequest)" is null
at cloud.piranha.extension.security.servlet.ServletSecurityManager.isRequestSecurityAsRequired(ServletSecurityManager.java:230)
at cloud.piranha.extension.exousia.AuthorizationPreFilter.doFilter(AuthorizationPreFilter.java:109)
at cloud.piranha.extension.exousia.AuthorizationPreFilter.doFilter(AuthorizationPreFilter.java:101)
at cloud.piranha.core.impl.DefaultFilterChain.doFilter(DefaultFilterChain.java:109)
at cloud.piranha.core.impl.DefaultServletRequestDispatcher.request(DefaultServletRequestDispatcher.java:162)
at cloud.piranha.core.impl.DefaultWebApplication.service(DefaultWebApplication.java:1213)
at cloud.piranha.http.webapp.HttpWebApplicationServer.service(HttpWebApplicationServer.java:177)
at cloud.piranha.http.webapp.HttpWebApplicationServer.process(HttpWebApplicationServer.java:133)
at cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:87)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by mnriem** [comment]
Unable to reproduce
