### ISSUE TITLE
Add JNDI to Piranha Server

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#733]
I was trying the Piranha Server 20.6.0-SNAPSHOT but nothing happened. After enable the logs, I could see that the server wasn't deploying correctly the admin-jmx application.

```
FINEST: CDI not available for app context id: server /admin-jmx
java.lang.IllegalStateException: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
	at org.glassfish.soteria.cdi.CdiUtils.jndiLookup(CdiUtils.java:207)
	at org.glassfish.soteria.cdi.CdiUtils.getBeanManager(CdiUtils.java:112)
	at org.glassfish.soteria.servlet.SamRegistrationInstaller.onStartup(SamRegistrationInstaller.java:66)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initializeInitializers(DefaultWebApplication.java:1307)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initialize(DefaultWebApplication.java:1258)
	at cloud.piranha.server.ServerPiranha.run(ServerPiranha.java:222)
	at cloud.piranha.server.ServerPiranha.main(ServerPiranha.java:104)
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:685)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:342)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
	at org.glassfish.soteria.cdi.CdiUtils.jndiLookup(CdiUtils.java:202)
	... 6 more

```

The problem was that  _java.naming.factory.initial_ wasn't defined, so it didn't deployed the application. 

I tried to use the DefaultInitialContextFactory, but it didn't work either.
This time the CdiUtils class from Soteria couldn't find the BeanManager and throw NPE.

```
Exception in thread "main" java.lang.NullPointerException
	at org.glassfish.soteria.cdi.CdiUtils.getBeanReferenceByType(CdiUtils.java:134)
	at org.glassfish.soteria.cdi.CdiUtils.getBeanReference(CdiUtils.java:127)
	at org.glassfish.soteria.servlet.SamRegistrationInstaller.onStartup(SamRegistrationInstaller.java:82)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initializeInitializers(DefaultWebApplication.java:1307)
	at cloud.piranha.webapp.impl.DefaultWebApplication.initialize(DefaultWebApplication.java:1258)
	at cloud.piranha.server.ServerPiranha.run(ServerPiranha.java:222)
	at cloud.piranha.server.ServerPiranha.main(ServerPiranha.java:104)
```

**Comment by manorrock** [comment]
This should fix the deployment problem. Feel free to give it another try now.
