### ISSUE TITLE
Piranha Micro fails using any extension except micro-servlet

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#837]
The only that works is micro-servlet because it's the only that contains a service file (cloud.piranha.webapp.api.WebApplicationExtension).

If we create the service file for the other extensions, we get different exceptions for each one

- Servlet (_-Dpiranha.extensions=micro-core,servlet_): java.lang.NoClassDefFoundError: cloud.piranha.jndi.memory.DefaultInitialContext
- WebProfile (_-Dpiranha.extensions=micro-core,webprofile_): java.lang.NoClassDefFoundError: javax.enterprise.context.spi.Contextual
- Apache WebProfile (_-Dpiranha.extensions=micro-core,apachewebprofile_): java.lang.NoClassDefFoundError: javax.enterprise.context.spi.Contextual

As I can tell, the Tomcat 9 extension doesn't fail to startup (_-Dpiranha.extensions=micro-core,tomcat9_). However, the JSP compilation is not working. (Should we include the JasperExtension in the other extensions too?)

For all of them we get the following warning: _ResourceManagerClassLoader not installed. This scanner does not work_ (cloud.piranha.webapp.annotationscan.AnnotationScanInitializer). I think some dependency is including the resource-api and the Piranha Micro already includes one version of it.

Including manually two dependencies (_-Dpiranha.dependencies=cloud.piranha.jndi:piranha-jndi-memory:20.6.0-SNAPSHOT,jakarta.platform:jakarta.jakartaee-web-api:8.0.0_), the Servlet extension works but both WebProfile extensions fails with the following error: 

```
WARNING: Initializer org.glassfish.soteria.servlet.SamRegistrationInstaller failing onStartup
java.lang.NullPointerException
    at org.glassfish.soteria.cdi.CdiUtils.getBeanReferenceByType(CdiUtils.java:134)
    at org.glassfish.soteria.cdi.CdiUtils.getBeanReference(CdiUtils.java:127)
    at org.glassfish.soteria.servlet.SamRegistrationInstaller.onStartup(SamRegistrationInstaller.java:82)
    at cloud.piranha.webapp.impl.DefaultWebApplication.initializeInitializers(DefaultWebApplication.java:1369)
    at cloud.piranha.webapp.impl.DefaultWebApplication.initialize(DefaultWebApplication.java:1320)
    at cloud.piranha.appserver.impl.DefaultWebApplicationServer.lambda$initialize$2(DefaultWebApplicationServer.java:231)
    at cloud.piranha.appserver.impl.DefaultWebApplicationServer$$Lambda$109/000000000C910350.accept(Unknown Source)
    at java.base/java.util.HashMap$Values.forEach(HashMap.java:1068)
    at cloud.piranha.appserver.impl.DefaultWebApplicationServer.initialize(DefaultWebApplicationServer.java:227)
    at cloud.piranha.micro.MicroInnerDeployer.start(MicroInnerDeployer.java:184)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at cloud.piranha.micro.MicroOuterDeployer.deploy(MicroOuterDeployer.java:162)
    at cloud.piranha.micro.MicroPiranha.run(MicroPiranha.java:131)
    at cloud.piranha.micro.MicroPiranha.main(MicroPiranha.java:73)

```

**Comment by manorrock** [comment]
Each of the extensions you are mentioning should only be used standalone and yes we need to get them all working. Note the Tomcat 9 extension should include everything needed to mimic Tomcat 9.

**Comment by Thihup** [comment]
Sure! I mean, only the Tomcat 9 extensions enable the Jasper extension. I was wondering if we should enable that extension in the Servlet and WebProfile too.

**Comment by manorrock** [comment]
Did this get resolved?

**Comment by Thihup** [comment]
Not yet. Only micro-servlet and microprofile extensions can be loaded through Service loader. However, I couldn't find a way that all extensions it will work in both Micro and Server.

**Comment by manorrock** [comment]
The end goal is to make Piranha Server operate in a similar matter as Piranha Micro. We might need to consider separating setting up the HTTP engine from setting up the web application

**Comment by manorrock** [comment]
Is this still an issue?

**Comment by Thihup** [comment]
I think the problems are with the extensions themselves, so this issue can be closed because the Piranha Micro indeed load the extensions
